from ConsignmentProject.components.data_ingestion import DataIngestion
from ConsignmentProject.components.data_cleaning import DataCleaning
from ConsignmentProject.components.data_validation import DataValidation