training_pipeline_config:
  artifact_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/wasimmadha/Datasets/master/SCMS_Delivery_History_Dataset.csv
  raw_data_dir: data_ingestion

data_cleaning_config:
  cleaned_file_dir: data_cleaning

data_validation_config:
  schema_dir: configs
  schema_file_name: schema.yaml

