from ConsignmentProject.entity.config_entity import DataIngestionConfig, DataPreTransformationConfig, TrainingPipelineConfig

from ConsignmentProject.entity.artifact_entity import DataIngestionArtifact, DataPreTransformationArtifact