from ConsignmentProject.entity.config_entity import DataIngestionConfig, DataPreTransformationConfig, TrainingPipelineConfig, DataValidationConfig

from ConsignmentProject.entity.artifact_entity import DataIngestionArtifact, DataPreTransformationArtifact, DataValidationArtifact